
version: "3"
services:
  cardano-explorer:
    build: ./explorer
    user: cardano
    volumes:
      - ./cardano-explorer/db:/home/cardano/cardano-sl/state-explorer-testnet/db
    ports:
      - 8100:8100
  cardano-http-bridge:
    build: ./cardano-http-bridge
    ports:
      - 8080:8080